# Construction du data set final

## Importation des données

In [1]:
import os
import subprocess
import pandas as pd
from datetime import datetime

### Données `df_ancestry_final`

In [2]:
name_of_file_in_bucket = "df_ancestry_final.tsv"

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/Data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
df_ancestry_final = pd.read_csv(name_of_file_in_bucket)
df_ancestry_final

Copying gs://fc-secure-f6bdc2c0-a989-46c1-930d-1f537d044b1f/Data/df_ancestry_final.tsv...
| [1 files][154.0 MiB/154.0 MiB]
Operation completed over 1 objects/154.0 MiB.

[INFO] df_ancestry_final.tsv is successfully downloaded into your working space

,research_id,ancestry_pred,afr_ancestry_prob,amr_ancestry_prob,eas_ancestry_prob,eur_ancestry_prob,mid_ancestry_prob,sas_ancestry_prob,ancestry_pred_other,PC1,...,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000000,afr,1.00,0.00,0.00,0.00,0.00,0.00,afr,-0.293561,...,-0.005621,-0.001204,-0.000920,0.006886,0.004709,0.004915,0.011461,0.002675,-0.001492,0.000896
1,1000004,eur,0.00,0.00,0.00,1.00,0.00,0.00,eur,0.101308,...,-0.011616,-0.001016,-0.001095,-0.000909,-0.001277,-0.000694,-0.000668,-0.000960,-0.001257,0.000115
2,1000033,eur,0.00,0.00,0.00,1.00,0.00,0.00,eur,0.098486,...,-0.018481,-0.001463,-0.001203,0.000465,0.000469,0.000629,0.000019,-0.000210,-0.000013,0.000411
3,1000039,afr,1.00,0.00,0.00,0.00,0.00,0.00,afr,-0.267138,...,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
4,1000042,afr,0.99,0.01,0.00,0.00,0.00,0.00,afr,-0.256277,...,0.003820,-0.002210,0.010388,-0.008314,-0.002740,0.003094,0.007370,0.001563,-0.002620,0.006765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414825,9999678,eur,0.00,0.00,0.00,0.99,0.00,0.01,eur,0.098743,...,-0.017846,-0.002502,-0.000634,0.000194,0.000252,-0.001290,0.001715,-0.000752,-0.000415,-0.000020
414826,9999697,amr,0.00,1.00,0.00,0.00,0.00,0.00,amr,0.085067,...,0.010985,0.002458,0.001513,-0.001535,-0.001271,-0.001320,-0.000950,-0.001408,-0.003327,0.000309
414827,9999715,eur,0.00,0.00,0.00,1.00,0.00,0.00,eur,0.099530,...,-0.015716,-0.002708,-0.001984,-0.001566,0.000294,0.000889,-0.001221,0.001146,-0.000401,0.000165
414828,9999755,eur,0.02,0.17,0.02,0.64,0.12,0.03,oth,0.064499,...,0.020151,0.001276,0.000953,-0.000316,-0.003218,0.000905,-0.000271,0.000847,0.001971,-0.000443
414829,9999860,eur,0.00,0.00,0.01,0.99,0.00,0.00,eur,0.099892,...,-0.010392,-0.001498,-0.000327,0.000432,-0.000195,-0.001229,0.000222,0.000455,-0.000527,0.000826

### Données `df_rye_final`

In [3]:
name_of_file_in_bucket = "df_rye_final.tsv"

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/Data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
df_rye_final = pd.read_csv(name_of_file_in_bucket)
df_rye_final.head()

Copying gs://fc-secure-f6bdc2c0-a989-46c1-930d-1f537d044b1f/Data/df_rye_final.tsv...
- [1 files][ 32.4 MiB/ 32.4 MiB]
Operation completed over 1 objects/32.4 MiB.

[INFO] df_rye_final.tsv is successfully downloaded into your working space

   research_id   eur_rye   eas_rye   amr_rye   afr_rye   sas_rye   mid_rye
0      1000000  0.000000  0.002611  0.000000  0.940905  0.000000  0.056484
1      1000004  0.892052  0.000000  0.063450  0.000000  0.000000  0.044498
2      1000033  0.886335  0.000000  0.039803  0.000000  0.073862  0.000000
3      1000039  0.045004  0.003594  0.000000  0.874350  0.003528  0.073524
4      1000042  0.115799  0.014158  0.000000  0.853614  0.000000  0.016430

### Données `plink_bed_files_array`

In [4]:
name_of_file_in_bucket = "df_plink_fam_files_array.tsv"

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/Data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
df_fam = pd.read_csv(name_of_file_in_bucket)
df_fam.head()

Copying gs://fc-secure-f6bdc2c0-a989-46c1-930d-1f537d044b1f/Data/df_plink_fam_files_array.tsv...
/ [1 files][  7.2 MiB/  7.2 MiB]
Operation completed over 1 objects/7.2 MiB.

[INFO] df_plink_fam_files_array.tsv is successfully downloaded into your working space

   A        B  C  D  E   F
0  0  1000000  0  0  0 NaN
1  0  1000004  0  0  0 NaN
2  0  1000033  0  0  0 NaN
3  0  1000039  0  0  0 NaN
4  0  1000042  0  0  0 NaN

### Cohort Breast Cancer (BC)

#### With Breast Cancer

In [5]:
name_of_file_in_bucket = "df_with_breast_cancer_final.tsv"

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/Data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
df_with_breast_cancer_final = pd.read_csv(name_of_file_in_bucket)
df_with_breast_cancer_final

Copying gs://fc-secure-f6bdc2c0-a989-46c1-930d-1f537d044b1f/Data/df_with_breast_cancer_final.tsv...
/ [1 files][ 1012 KiB/ 1012 KiB]
Operation completed over 1 objects/1012.5 KiB.

[INFO] df_with_breast_cancer_final.tsv is successfully downloaded into your working space

,person_id,gender,date_of_birth,race,ethnicity,self_reported_category,has_BC
0,2011636,Female,1937-06-15 00:00:00+00:00,American Indian or Alaska Native,Not Hispanic or Latino,American Indian or Alaska Native,1
1,7280114,Female,1948-06-15 00:00:00+00:00,American Indian or Alaska Native,Not Hispanic or Latino,American Indian or Alaska Native,1
2,2253660,Female,1956-06-15 00:00:00+00:00,American Indian or Alaska Native,Not Hispanic or Latino,American Indian or Alaska Native,1
3,5832436,Female,1952-06-15 00:00:00+00:00,American Indian or Alaska Native,Not Hispanic or Latino,American Indian or Alaska Native,1
4,1340234,Female,1960-06-15 00:00:00+00:00,American Indian or Alaska Native,Not Hispanic or Latino,American Indian or Alaska Native,1
...,...,...,...,...,...,...,...
11734,1951816,Female,1978-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,1
11735,1390558,Female,1979-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,1
11736,8233973,Female,1981-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,1
11737,2877487,Female,1988-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,1
11738,1887014,Female,1995-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,1

#### Not Breast Cancer

In [6]:
name_of_file_in_bucket = "df_not_breast_cancer_final.tsv"

# get the bucket name
my_bucket = os.getenv('WORKSPACE_BUCKET')

# copy csv file from the bucket to the current working space
os.system(f"gsutil cp '{my_bucket}/Data/{name_of_file_in_bucket}' .")

print(f'[INFO] {name_of_file_in_bucket} is successfully downloaded into your working space')
# save dataframe in a csv file in the same workspace as the notebook
df_not_breast_cancer_final = pd.read_csv(name_of_file_in_bucket)
df_not_breast_cancer_final

Copying gs://fc-secure-f6bdc2c0-a989-46c1-930d-1f537d044b1f/Data/df_not_breast_cancer_final.tsv...
/ [1 files][ 33.4 MiB/ 33.4 MiB]
Operation completed over 1 objects/33.4 MiB.

[INFO] df_not_breast_cancer_final.tsv is successfully downloaded into your working space

,person_id,gender,date_of_birth,race,ethnicity,self_reported_category,has_BC
0,1104573,Female,1996-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0
1,9817954,Female,1979-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0
2,1163679,Female,1965-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0
3,9158204,Female,1988-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0
4,2300102,Female,1951-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0
...,...,...,...,...,...,...,...
379066,5683164,Female,1966-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0
379067,7834223,Female,1981-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0
379068,2022233,Female,1946-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0
379069,1549231,Female,1983-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0
379070,1615313,Female,1987-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0

## Fusion des jeux de données

### Merge `df_ancestry_final` / `df_rye`

In [7]:
# Fusion des jeux de données RYE et Ancestry sur la clé 'research_id' (jointure interne)
df_merged = df_rye_final.merge(df_ancestry_final, on='research_id', how='inner')

### Merge `df_with_breast_cancer` / `df_not_breast_cancer`

In [8]:
# Regroupement des individus avec et sans cancer du sein dans un seul DataFrame
df_bc = pd.concat([df_with_breast_cancer_final, df_not_breast_cancer_final], ignore_index=True)

### Merge `df_bc` / `df_bam`

In [9]:
# Ajoute une colonne "FID" en première position du DataFrame `df_bc`, en copiant les valeurs de "person_id"
df_bc.insert(0, "FID", df_bc.person_id)

In [10]:
# Fusionne les individus présents dans le fichier .fam avec le DataFrame `df_bc` via la colonne "person_id"
df_bc_fam = df_fam[['B']].merge(df_bc, left_on="B", right_on="person_id", how="inner").drop(columns=['FID','person_id'])

### Merge `df_bc_fam` /  `df_merged`

In [11]:
# Fusionne les données de génotypage et d’ancestry avec les données phénotypiques, puis supprime la colonne redondante "research_id"
df_merged_all = df_bc_fam.merge(df_merged, left_on='B', right_on='research_id', how='left').drop(columns=['research_id','gender'])

In [12]:
df_merged_all

,B,date_of_birth,race,ethnicity,self_reported_category,has_BC,eur_rye,eas_rye,amr_rye,afr_rye,...,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000039,1971-06-15 00:00:00+00:00,Black or African American,Not Hispanic or Latino,Black or African American,0,0.045004,0.003594,0.000000,0.874350,...,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
1,1000045,1958-06-15 00:00:00+00:00,Asian,Not Hispanic or Latino,Asian,0,0.000000,0.939365,0.000000,0.007806,...,0.001778,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426
2,1000059,1957-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,0,0.781992,0.000000,0.120046,0.000000,...,-0.010278,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093
3,1000062,1959-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,0,0.783972,0.000952,0.091612,0.000000,...,-0.011289,-0.000806,-0.000868,0.000160,0.000223,-0.000703,0.000848,-0.000522,0.000670,0.000393
4,1000070,1947-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,0,0.894111,0.000000,0.050451,0.000000,...,-0.017076,-0.002684,-0.002102,0.000015,0.000914,-0.000492,-0.000415,-0.001789,0.001531,-0.000028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267159,9999373,1972-06-15 00:00:00+00:00,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0,0.987243,0.000000,0.000000,0.012757,...,-0.019134,-0.004776,-0.001668,-0.001610,0.000282,-0.000176,-0.000780,-0.001432,-0.001350,-0.000589
267160,9999653,1982-06-15 00:00:00+00:00,Black or African American,Hispanic or Latino,More than one population,0,0.070018,0.031847,0.459473,0.419679,...,-0.007309,0.007351,-0.003693,-0.002859,-0.003085,-0.000890,0.006171,0.006674,0.003420,0.004854
267161,9999678,1964-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,0,0.913647,0.000000,0.028156,0.000000,...,-0.017846,-0.002502,-0.000634,0.000194,0.000252,-0.001290,0.001715,-0.000752,-0.000415,-0.000020
267162,9999697,1986-06-15 00:00:00+00:00,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0,0.000000,0.000000,0.947722,0.000000,...,0.010985,0.002458,0.001513,-0.001535,-0.001271,-0.001320,-0.000950,-0.001408,-0.003327,0.000309
267163,9999860,2000-06-15 00:00:00+00:00,White,Not Hispanic or Latino,White,0,0.862893,0.000000,0.032371,0.000000,...,-0.010392,-0.001498,-0.000327,0.000432,-0.000195,-0.001229,0.000222,0.000455,-0.000527,0.000826

## Traitement des données manquantes

In [13]:
# Affiche le nombre de valeurs manquantes pour chaque colonne du DataFrame fusionné
df_merged_all.isna().sum()

B                             0
date_of_birth                 0
race                          0
ethnicity                     0
self_reported_category        0
has_BC                        0
eur_rye                   19529
eas_rye                   19529
amr_rye                   19529
afr_rye                   19529
sas_rye                   19529
mid_rye                   19529
ancestry_pred             19529
afr_ancestry_prob         19529
amr_ancestry_prob         19529
eas_ancestry_prob         19529
eur_ancestry_prob         19529
mid_ancestry_prob         19529
sas_ancestry_prob         19529
ancestry_pred_other       19529
PC1                       19529
PC2                       19529
PC3                       19529
PC4                       19529
PC5                       19529
PC6                       19529
PC7                       19529
PC8                       19529
PC9                       19529
PC10                      19529
PC11                      19529
PC12                      19529
PC13                      19529
PC14                      19529
PC15                      19529
PC16                      19529
dtype: int64

In [14]:
# Remplace toutes les valeurs manquantes du DataFrame par 0
df_merged_all_not_nan = df_merged_all.fillna(0)

## Features engineering

### Ajout d'une colonne age

In [15]:
# Convertit les dates de naissance en format datetime, puis calcule l'âge à partir de l'année en cours
df_merged_all_not_nan['date_of_birth'] = pd.to_datetime(df_merged_all_not_nan['date_of_birth'])
current_year = datetime.now().year
df_merged_all_not_nan['age'] = current_year - df_merged_all_not_nan['date_of_birth'].dt.year

df_merged_all_not_nan.drop(columns="date_of_birth", inplace=True)
df_merged_all_not_nan

,B,race,ethnicity,self_reported_category,has_BC,eur_rye,eas_rye,amr_rye,afr_rye,sas_rye,...,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,age
0,1000039,Black or African American,Not Hispanic or Latino,Black or African American,0,0.045004,0.003594,0.000000,0.874350,0.003528,...,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376,55
1,1000045,Asian,Not Hispanic or Latino,Asian,0,0.000000,0.939365,0.000000,0.007806,0.031606,...,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426,68
2,1000059,White,Not Hispanic or Latino,White,0,0.781992,0.000000,0.120046,0.000000,0.028276,...,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093,69
3,1000062,White,Not Hispanic or Latino,White,0,0.783972,0.000952,0.091612,0.000000,0.042836,...,-0.000806,-0.000868,0.000160,0.000223,-0.000703,0.000848,-0.000522,0.000670,0.000393,67
4,1000070,White,Not Hispanic or Latino,White,0,0.894111,0.000000,0.050451,0.000000,0.041453,...,-0.002684,-0.002102,0.000015,0.000914,-0.000492,-0.000415,-0.001789,0.001531,-0.000028,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267159,9999373,None of these,What Race Ethnicity: Race Ethnicity None Of These,None of these,0,0.987243,0.000000,0.000000,0.012757,0.000000,...,-0.004776,-0.001668,-0.001610,0.000282,-0.000176,-0.000780,-0.001432,-0.001350,-0.000589,54
267160,9999653,Black or African American,Hispanic or Latino,More than one population,0,0.070018,0.031847,0.459473,0.419679,0.001824,...,0.007351,-0.003693,-0.002859,-0.003085,-0.000890,0.006171,0.006674,0.003420,0.004854,44
267161,9999678,White,Not Hispanic or Latino,White,0,0.913647,0.000000,0.028156,0.000000,0.029290,...,-0.002502,-0.000634,0.000194,0.000252,-0.001290,0.001715,-0.000752,-0.000415,-0.000020,62
267162,9999697,None Indicated,Hispanic or Latino,What Race Ethnicity: Hispanic,0,0.000000,0.000000,0.947722,0.000000,0.032638,...,0.002458,0.001513,-0.001535,-0.001271,-0.001320,-0.000950,-0.001408,-0.003327,0.000309,40
267163,9999860,White,Not Hispanic or Latino,White,0,0.862893,0.000000,0.032371,0.000000,0.022134,...,-0.001498,-0.000327,0.000432,-0.000195,-0.001229,0.000222,0.000455,-0.000527,0.000826,26

In [16]:
col = 'age'

# Déplacer la colonne 'age' à la 4ᵉ position (index 3) du DataFrame
col_data = df_merged_all_not_nan.pop(col)
df_merged_all_not_nan.insert(3, col, col_data)
df_merged_all_not_nan

,B,race,ethnicity,age,self_reported_category,has_BC,eur_rye,eas_rye,amr_rye,afr_rye,...,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000039,Black or African American,Not Hispanic or Latino,55,Black or African American,0,0.045004,0.003594,0.000000,0.874350,...,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
1,1000045,Asian,Not Hispanic or Latino,68,Asian,0,0.000000,0.939365,0.000000,0.007806,...,0.001778,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426
2,1000059,White,Not Hispanic or Latino,69,White,0,0.781992,0.000000,0.120046,0.000000,...,-0.010278,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093
3,1000062,White,Not Hispanic or Latino,67,White,0,0.783972,0.000952,0.091612,0.000000,...,-0.011289,-0.000806,-0.000868,0.000160,0.000223,-0.000703,0.000848,-0.000522,0.000670,0.000393
4,1000070,White,Not Hispanic or Latino,79,White,0,0.894111,0.000000,0.050451,0.000000,...,-0.017076,-0.002684,-0.002102,0.000015,0.000914,-0.000492,-0.000415,-0.001789,0.001531,-0.000028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267159,9999373,None of these,What Race Ethnicity: Race Ethnicity None Of These,54,None of these,0,0.987243,0.000000,0.000000,0.012757,...,-0.019134,-0.004776,-0.001668,-0.001610,0.000282,-0.000176,-0.000780,-0.001432,-0.001350,-0.000589
267160,9999653,Black or African American,Hispanic or Latino,44,More than one population,0,0.070018,0.031847,0.459473,0.419679,...,-0.007309,0.007351,-0.003693,-0.002859,-0.003085,-0.000890,0.006171,0.006674,0.003420,0.004854
267161,9999678,White,Not Hispanic or Latino,62,White,0,0.913647,0.000000,0.028156,0.000000,...,-0.017846,-0.002502,-0.000634,0.000194,0.000252,-0.001290,0.001715,-0.000752,-0.000415,-0.000020
267162,9999697,None Indicated,Hispanic or Latino,40,What Race Ethnicity: Hispanic,0,0.000000,0.000000,0.947722,0.000000,...,0.010985,0.002458,0.001513,-0.001535,-0.001271,-0.001320,-0.000950,-0.001408,-0.003327,0.000309
267163,9999860,White,Not Hispanic or Latino,26,White,0,0.862893,0.000000,0.032371,0.000000,...,-0.010392,-0.001498,-0.000327,0.000432,-0.000195,-0.001229,0.000222,0.000455,-0.000527,0.000826

## Exportation des données

In [17]:
# Enregistre le DataFrame final dans un fichier TSV local
destination_filename = 'df_final_cohort.tsv'
df_merged_all_not_nan.to_csv(destination_filename, index=False)

# Récupère le nom du bucket de l'environnement d'exécution
my_bucket = os.getenv('WORKSPACE_BUCKET')

# Copie le fichier TSV local vers le dossier "Data" du bucket Google Cloud
args = ["gsutil", "cp", f"./{destination_filename}", f"{my_bucket}/Data/"]
output = subprocess.run(args, capture_output=True)

# Affiche les éventuels messages d’erreur de la commande gsutil
output.stderr

b'Copying file://./df_final_cohort.tsv [Content-Type=text/tab-separated-values]...\n/ [0 files][    0.0 B/117.0 MiB]                                                \r-\r- [0 files][  3.1 MiB/117.0 MiB]                                                \r\\\r\\ [0 files][  4.9 MiB/117.0 MiB]                                                \r|\r/\r/ [0 files][  6.7 MiB/117.0 MiB]                                                \r-\r- [0 files][  8.5 MiB/117.0 MiB]                                                \r\\\r|\r| [0 files][ 10.3 MiB/117.0 MiB]                                                \r/\r/ [0 files][ 12.1 MiB/117.0 MiB]                                                \r-\r- [0 files][ 13.9 MiB/117.0 MiB]                                                \r\\\r|\r| [0 files][ 15.7 MiB/117.0 MiB]                                                \r/\r/ [0 files][ 17.5 MiB/117.0 MiB]                                                \r-\r\\\r\\ [0 files][ 19.3 MiB/117.0 MiB]                                                \r|\r| [0 files][ 21.1 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 23.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r\\\r\\ [0 files][ 24.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 26.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][ 28.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 30.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 32.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][ 33.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 35.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][ 37.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 39.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 41.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][ 42.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 44.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r|\r| [0 files][ 46.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 48.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 50.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r|\r| [0 files][ 51.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 53.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r\\\r\\ [0 files][ 55.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 57.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 59.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r\\\r\\ [0 files][ 60.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 62.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][ 64.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 66.3 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 68.1 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][ 69.9 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 71.7 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][ 73.5 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 75.3 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][ 77.1 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][ 78.9 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 80.7 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r|\r| [0 files][ 82.5 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 84.3 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][ 86.1 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r|\r| [0 files][ 87.9 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 89.7 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r\\\r\\ [0 files][ 91.5 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 93.3 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r/ [0 files][ 95.1 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r\\\r\\ [0 files][ 96.9 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][ 98.7 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][100.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][102.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r| [0 files][104.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r/\r-\r- [0 files][106.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][107.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][109.6 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][111.4 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [0 files][113.2 MiB/117.0 MiB]    1.8 MiB/s                                   \r|\r/\r/ [0 files][115.0 MiB/117.0 MiB]    1.8 MiB/s                                   \r-\r- [0 files][116.8 MiB/117.0 MiB]    1.8 MiB/s                                   \r\\\r\\ [1 files][117.0 MiB/117.0 MiB]    1.4 MiB/s                                   \r|\r\nOperation completed over 1 objects/117.0 MiB.                                    \n'