In [83]:
import pandas
import os

# This query represents dataset "Woman BC invasive" for domain "person" and was generated for All of Us Controlled Tier Dataset v8
dataset_13503019_person_sql = """
    SELECT
        person.person_id,
        person.gender_concept_id,
        p_gender_concept.concept_name as gender,
        person.birth_datetime as date_of_birth,
        person.race_concept_id,
        p_race_concept.concept_name as race,
        person.ethnicity_concept_id,
        p_ethnicity_concept.concept_name as ethnicity,
        person.sex_at_birth_concept_id,
        p_sex_at_birth_concept.concept_name as sex_at_birth,
        person.self_reported_category_concept_id,
        p_self_reported_category_concept.concept_name as self_reported_category 
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.person` person 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_gender_concept 
            ON person.gender_concept_id = p_gender_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_race_concept 
            ON person.race_concept_id = p_race_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_ethnicity_concept 
            ON person.ethnicity_concept_id = p_ethnicity_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_sex_at_birth_concept 
            ON person.sex_at_birth_concept_id = p_sex_at_birth_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_self_reported_category_concept 
            ON person.self_reported_category_concept_id = p_self_reported_category_concept.concept_id  
    WHERE
        person.PERSON_ID IN (SELECT
            distinct person_id  
        FROM
            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
        WHERE
            cb_search_person.person_id IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                WHERE
                    (concept_id IN(SELECT
                        DISTINCT c.concept_id 
                    FROM
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                    JOIN
                        (SELECT
                            CAST(cr.id as string) AS id       
                        FROM
                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr       
                        WHERE
                            concept_id IN (44819434, 1567537)       
                            AND full_text LIKE '%_rank1]%'      ) a 
                            ON (c.path LIKE CONCAT('%.', a.id, '.%') 
                            OR c.path LIKE CONCAT('%.', a.id) 
                            OR c.path LIKE CONCAT(a.id, '.%') 
                            OR c.path = a.id) 
                    WHERE
                        is_standard = 0 
                        AND is_selectable = 1) 
                    AND is_standard = 0 )) criteria ) 
            AND cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `""" + os.environ["WORKSPACE_CDR"] + """.person` p 
            WHERE
                gender_concept_id IN (45878463) ) )"""

dataset_13503019_person_df = pandas.read_gbq(
    dataset_13503019_person_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook")

dataset_13503019_person_df.head(5)

Downloading:   0%|          | 0/11725 [00:00<?, ?rows/s]

,person_id,gender_concept_id,gender,date_of_birth,race_concept_id,race,ethnicity_concept_id,ethnicity,sex_at_birth_concept_id,sex_at_birth,self_reported_category_concept_id,self_reported_category
0,1151360,45878463,Female,1974-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,0,No matching concept,8515,Asian
1,2099030,45878463,Female,1940-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,903096,PMI: Skip,8515,Asian
2,3173790,45878463,Female,1954-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,903096,PMI: Skip,8515,Asian
3,1462413,45878463,Female,1949-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,903096,PMI: Skip,8515,Asian
4,5363674,45878463,Female,1973-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,45880669,Male,8515,Asian

In [84]:
import pandas
import os

# This query represents dataset "Women NON BC invasive" for domain "person" and was generated for All of Us Controlled Tier Dataset v8
dataset_08407181_person_sql = """
    SELECT
        person.person_id,
        person.gender_concept_id,
        p_gender_concept.concept_name as gender,
        person.birth_datetime as date_of_birth,
        person.race_concept_id,
        p_race_concept.concept_name as race,
        person.ethnicity_concept_id,
        p_ethnicity_concept.concept_name as ethnicity,
        person.sex_at_birth_concept_id,
        p_sex_at_birth_concept.concept_name as sex_at_birth,
        person.self_reported_category_concept_id,
        p_self_reported_category_concept.concept_name as self_reported_category 
    FROM
        `""" + os.environ["WORKSPACE_CDR"] + """.person` person 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_gender_concept 
            ON person.gender_concept_id = p_gender_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_race_concept 
            ON person.race_concept_id = p_race_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_ethnicity_concept 
            ON person.ethnicity_concept_id = p_ethnicity_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_sex_at_birth_concept 
            ON person.sex_at_birth_concept_id = p_sex_at_birth_concept.concept_id 
    LEFT JOIN
        `""" + os.environ["WORKSPACE_CDR"] + """.concept` p_self_reported_category_concept 
            ON person.self_reported_category_concept_id = p_self_reported_category_concept.concept_id  
    WHERE
        person.PERSON_ID IN (SELECT
            distinct person_id  
        FROM
            `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_person` cb_search_person  
        WHERE
            cb_search_person.person_id IN (SELECT
                person_id 
            FROM
                `""" + os.environ["WORKSPACE_CDR"] + """.person` p 
            WHERE
                gender_concept_id IN (45878463) ) 
            AND cb_search_person.person_id NOT IN (SELECT
                criteria.person_id 
            FROM
                (SELECT
                    DISTINCT person_id, entry_date, concept_id 
                FROM
                    `""" + os.environ["WORKSPACE_CDR"] + """.cb_search_all_events` 
                WHERE
                    (concept_id IN(SELECT
                        DISTINCT c.concept_id 
                    FROM
                        `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` c 
                    JOIN
                        (SELECT
                            CAST(cr.id as string) AS id       
                        FROM
                            `""" + os.environ["WORKSPACE_CDR"] + """.cb_criteria` cr       
                        WHERE
                            concept_id IN (44819434, 1567537)       
                            AND full_text LIKE '%_rank1]%'      ) a 
                            ON (c.path LIKE CONCAT('%.', a.id, '.%') 
                            OR c.path LIKE CONCAT('%.', a.id) 
                            OR c.path LIKE CONCAT(a.id, '.%') 
                            OR c.path = a.id) 
                    WHERE
                        is_standard = 0 
                        AND is_selectable = 1) 
                    AND is_standard = 0 )) criteria ) )"""

dataset_08407181_person_df = pandas.read_gbq(
    dataset_08407181_person_sql,
    dialect="standard",
    use_bqstorage_api=("BIGQUERY_STORAGE_API_ENABLED" in os.environ),
    progress_bar_type="tqdm_notebook")

dataset_08407181_person_df.head(5)

Downloading:   0%|          | 0/379085 [00:00<?, ?rows/s]

,person_id,gender_concept_id,gender,date_of_birth,race_concept_id,race,ethnicity_concept_id,ethnicity,sex_at_birth_concept_id,sex_at_birth,self_reported_category_concept_id,self_reported_category
0,8556331,45878463,Female,1972-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,1585849,Sex At Birth: Sex At Birth None Of These,8515,Asian
1,8053281,45878463,Female,1952-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,1585849,Sex At Birth: Sex At Birth None Of These,8515,Asian
2,3339784,45878463,Female,1999-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,1585849,Sex At Birth: Sex At Birth None Of These,8515,Asian
3,8582996,45878463,Female,1958-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,903096,PMI: Skip,8515,Asian
4,4780567,45878463,Female,1978-06-15 00:00:00+00:00,8515,Asian,38003564,Not Hispanic or Latino,903096,PMI: Skip,8515,Asian

In [85]:
dataset_13503019_person_df['has_BC'] = 1
dataset_08407181_person_df['has_BC'] = 0

In [86]:
import pandas as pd

cols_to_keep = ['person_id', 'date_of_birth', 'has_BC']
df1_filtered = dataset_13503019_person_df[cols_to_keep]
df2_filtered = dataset_08407181_person_df[cols_to_keep]

# 2. Concaténer verticalement
Women_bc_ctr_concat = pd.concat([df1_filtered, df2_filtered], ignore_index=True)

# Ajoute colonne age

In [87]:
from datetime import datetime
import pandas as pd

Women_bc_ctr_concat['date_of_birth'] = pd.to_datetime(Women_bc_ctr_concat['date_of_birth'])
current_year = datetime.now().year
Women_bc_ctr_concat['age'] = current_year - Women_bc_ctr_concat['date_of_birth'].dt.year

Women_bc_ctr_concat

        person_id             date_of_birth  has_BC  age
0         1151360 1974-06-15 00:00:00+00:00       1   51
1         2099030 1940-06-15 00:00:00+00:00       1   85
2         3173790 1954-06-15 00:00:00+00:00       1   71
3         1462413 1949-06-15 00:00:00+00:00       1   76
4         5363674 1973-06-15 00:00:00+00:00       1   52
...           ...                       ...     ...  ...
390805    5650430 2003-06-15 00:00:00+00:00       0   22
390806    2739477 2004-06-15 00:00:00+00:00       0   21
390807    9291263 2004-06-15 00:00:00+00:00       0   21
390808    6516468 2004-06-15 00:00:00+00:00       0   21
390809    3429096 2005-06-15 00:00:00+00:00       0   20

[390810 rows x 4 columns]

# Ajoute 16 PCA

In [1]:
!gsutil -u $GOOGLE_PROJECT cp gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv .

Copying gs://fc-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/ancestry/ancestry_preds.tsv...
\ [1 files][163.4 MiB/163.4 MiB]
Operation completed over 1 objects/163.4 MiB.

In [89]:
ancestry_pred = pd.read_csv("ancestry_preds.tsv", delimiter="\t")
ancestry_pred

,research_id,ancestry_pred,probabilities,pca_features,ancestry_pred_other
0,1000000,afr,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[-0.29356093859992993, -0.006344531427051658, ...",afr
1,1000004,eur,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0]","[0.10130837407349723, 0.13870298220174238, 0.0...",eur
2,1000033,eur,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0]","[0.09848604976046149, 0.1245991833533566, 0.00...",eur
3,1000039,afr,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[-0.26713841551900935, 0.00469795004195689, 0....",afr
4,1000042,afr,"[0.99, 0.01, 0.0, 0.0, 0.0, 0.0]","[-0.2562773941608334, 0.004901392894403225, -0...",afr
...,...,...,...,...,...
414825,9999678,eur,"[0.0, 0.0, 0.0, 0.99, 0.0, 0.01]","[0.09874274635571259, 0.13176851496404074, 0.0...",eur
414826,9999697,amr,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]","[0.08506698802084682, 0.028602321968432515, -0...",amr
414827,9999715,eur,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0]","[0.0995298469352078, 0.13283576852436813, 0.00...",eur
414828,9999755,eur,"[0.02, 0.17, 0.02, 0.64, 0.12, 0.03]","[0.06449853461869955, 0.11663708597332126, 0.0...",oth
414829,9999860,eur,"[0.0, 0.0, 0.01, 0.99, 0.0, 0.0]","[0.09989172429511081, 0.1338690082030004, 0.01...",eur

In [90]:
ancestry_pred["pca_features"] = ancestry_pred["pca_features"].str[1:-1]

In [91]:
PCs = ancestry_pred["pca_features"].str.split(",", n = 16, expand = True)
PCs = PCs.astype(float)

In [92]:
pid = ancestry_pred[["research_id"]]
pid.head(5)

   research_id
0      1000000
1      1000004
2      1000033
3      1000039
4      1000042

In [93]:
columns= ["PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10","PC11","PC12","PC13","PC14","PC15","PC16"]
PCs.columns = columns

In [94]:
PCs.head(5)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,-0.293561,-0.006345,0.002386,0.001446,0.024304,-0.001529,-0.005621,-0.001204,-0.000920,0.006886,0.004709,0.004915,0.011461,0.002675,-0.001492,0.000896
1,0.101308,0.138703,0.006683,0.053012,0.003345,0.019714,-0.011616,-0.001016,-0.001095,-0.000909,-0.001277,-0.000694,-0.000668,-0.000960,-0.001257,0.000115
2,0.098486,0.124599,0.009398,0.042617,0.003846,0.026659,-0.018481,-0.001463,-0.001203,0.000465,0.000469,0.000629,0.000019,-0.000210,-0.000013,0.000411
3,-0.267138,0.004698,0.001046,0.001767,0.031375,0.001713,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
4,-0.256277,0.004901,-0.002448,0.009514,0.008931,0.010683,0.003820,-0.002210,0.010388,-0.008314,-0.002740,0.003094,0.007370,0.001563,-0.002620,0.006765

In [95]:
PCs_final = pd.concat([pid, PCs], axis = 1)
PCs_final.head(5)

,research_id,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000000,-0.293561,-0.006345,0.002386,0.001446,0.024304,-0.001529,-0.005621,-0.001204,-0.000920,0.006886,0.004709,0.004915,0.011461,0.002675,-0.001492,0.000896
1,1000004,0.101308,0.138703,0.006683,0.053012,0.003345,0.019714,-0.011616,-0.001016,-0.001095,-0.000909,-0.001277,-0.000694,-0.000668,-0.000960,-0.001257,0.000115
2,1000033,0.098486,0.124599,0.009398,0.042617,0.003846,0.026659,-0.018481,-0.001463,-0.001203,0.000465,0.000469,0.000629,0.000019,-0.000210,-0.000013,0.000411
3,1000039,-0.267138,0.004698,0.001046,0.001767,0.031375,0.001713,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
4,1000042,-0.256277,0.004901,-0.002448,0.009514,0.008931,0.010683,0.003820,-0.002210,0.010388,-0.008314,-0.002740,0.003094,0.007370,0.001563,-0.002620,0.006765

In [96]:
pheno_final = Women_bc_ctr_concat.merge(PCs_final, left_on = "person_id", right_on = "research_id", how = "left").drop(["research_id","date_of_birth"], axis = 1)
pheno_final

,person_id,has_BC,age,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1151360,1,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2099030,1,85,0.086004,0.027196,0.041991,-0.089245,-0.000932,0.010132,-0.006099,-0.001171,0.000238,0.000483,-0.000127,-0.000038,0.001236,-0.001882,0.000156,0.001678
2,3173790,1,71,0.102128,0.128736,0.009761,0.053561,0.003930,0.027566,-0.021088,-0.002865,-0.003005,0.000758,-0.000440,-0.000949,-0.000299,-0.000181,-0.000250,-0.000870
3,1462413,1,76,0.100597,-0.172112,0.045214,0.040481,-0.000183,-0.003130,0.003553,-0.000222,-0.000369,0.000667,0.000811,0.000355,-0.000104,0.000805,0.001066,-0.000257
4,5363674,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390805,5650430,0,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390806,2739477,0,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390807,9291263,0,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390808,6516468,0,21,0.098766,0.128672,0.013632,0.046796,0.002850,0.022634,-0.016498,-0.001171,-0.000914,0.001650,-0.000943,0.000415,-0.000954,-0.001645,0.001419,-0.000475
390809,3429096,0,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
pheno_final.insert(0, "FID", pheno_final.person_id)
pheno_final.head(5)

,FID,person_id,has_BC,age,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1151360,1151360,1,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2099030,2099030,1,85,0.086004,0.027196,0.041991,-0.089245,-0.000932,0.010132,-0.006099,-0.001171,0.000238,0.000483,-0.000127,-0.000038,0.001236,-0.001882,0.000156,0.001678
2,3173790,3173790,1,71,0.102128,0.128736,0.009761,0.053561,0.003930,0.027566,-0.021088,-0.002865,-0.003005,0.000758,-0.000440,-0.000949,-0.000299,-0.000181,-0.000250,-0.000870
3,1462413,1462413,1,76,0.100597,-0.172112,0.045214,0.040481,-0.000183,-0.003130,0.003553,-0.000222,-0.000369,0.000667,0.000811,0.000355,-0.000104,0.000805,0.001066,-0.000257
4,5363674,5363674,1,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
fam = pd.read_csv("plink/arrays.fam", delimiter = "\t",
                  names = ["A","B","C","D","E","F"])
fam.head(3)

   A        B  C  D  E   F
0  0  1000000  0  0  0 NaN
1  0  1000004  0  0  0 NaN
2  0  1000033  0  0  0 NaN

In [99]:
pheno_new = fam.merge(pheno_final, left_on = "B", right_on = "person_id", how = "inner")

,A,B,C,D,E,F,FID,person_id,has_BC,age,...,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,0,1000039,0,0,0,NaN,1000039,1000039,0,54,...,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
1,0,1000045,0,0,0,NaN,1000045,1000045,0,67,...,0.001778,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426
2,0,1000059,0,0,0,NaN,1000059,1000059,0,68,...,-0.010278,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093
3,0,1000062,0,0,0,NaN,1000062,1000062,0,66,...,-0.011289,-0.000806,-0.000868,0.000160,0.000223,-0.000703,0.000848,-0.000522,0.000670,0.000393
4,0,1000070,0,0,0,NaN,1000070,1000070,0,78,...,-0.017076,-0.002684,-0.002102,0.000015,0.000914,-0.000492,-0.000415,-0.001789,0.001531,-0.000028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267159,0,9999373,0,0,0,NaN,9999373,9999373,0,53,...,-0.019134,-0.004776,-0.001668,-0.001610,0.000282,-0.000176,-0.000780,-0.001432,-0.001350,-0.000589
267160,0,9999653,0,0,0,NaN,9999653,9999653,0,43,...,-0.007309,0.007351,-0.003693,-0.002859,-0.003085,-0.000890,0.006171,0.006674,0.003420,0.004854
267161,0,9999678,0,0,0,NaN,9999678,9999678,0,61,...,-0.017846,-0.002502,-0.000634,0.000194,0.000252,-0.001290,0.001715,-0.000752,-0.000415,-0.000020
267162,0,9999697,0,0,0,NaN,9999697,9999697,0,39,...,0.010985,0.002458,0.001513,-0.001535,-0.001271,-0.001320,-0.000950,-0.001408,-0.003327,0.000309
267163,0,9999860,0,0,0,NaN,9999860,9999860,0,25,...,-0.010392,-0.001498,-0.000327,0.000432,-0.000195,-0.001229,0.000222,0.000455,-0.000527,0.000826

In [115]:
import numpy as np
pheno_out = pheno_new.iloc[:,np.r_[1,1,8:26]]
pheno_out.head(3)

,B,B,has_BC,age,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000039,1000039,0,54,-0.267138,0.004698,0.001046,0.001767,0.031375,0.001713,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
1,1000045,1000045,0,67,0.097379,-0.158116,0.044858,0.033242,0.000106,-0.004703,0.001778,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426
2,1000059,1000059,0,68,0.101533,0.131331,0.003037,0.043757,0.002176,0.016036,-0.010278,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093

In [116]:
pheno_out = pheno_out.fillna(0)
pheno_out.head(3)

,B,B,has_BC,age,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16
0,1000039,1000039,0,54,-0.267138,0.004698,0.001046,0.001767,0.031375,0.001713,-0.009450,0.016385,-0.000844,0.001511,0.003544,-0.000247,-0.010346,0.005279,-0.013716,0.008376
1,1000045,1000045,0,67,0.097379,-0.158116,0.044858,0.033242,0.000106,-0.004703,0.001778,0.000698,-0.000009,0.000727,-0.000209,0.000062,-0.000256,-0.000293,-0.000274,-0.000426
2,1000059,1000059,0,68,0.101533,0.131331,0.003037,0.043757,0.002176,0.016036,-0.010278,-0.001716,-0.000227,0.000956,0.000586,-0.001687,0.000547,-0.001534,0.001173,-0.000093

In [117]:
pheno_out.to_csv("pheno_plink.tsv", index = False, header = False, sep = "\t")

In [118]:
bucket = os.getenv("WORKSPACE_BUCKET")
!gsutil -m cp pheno_plink.tsv {bucket}/Data/

Copying file://pheno_plink.tsv [Content-Type=text/tab-separated-values]...
- [1/1 files][ 88.7 MiB/ 88.7 MiB] 100% Done   1.4 MiB/s ETA 00:00:00
Operation completed over 1 objects/88.7 MiB.