# Import Environment variables

In [1]:
%run /home/jupyter/repos/Multi-trait-GWAS-in-admixed-populations/notebooks/Setting_Env_Variables.ipynb

Found bucket: id=rw-migration-aou-rw-f7a4d148, bucketName=rw-migration-aou-rw-f7a4d148
-> Assigned migration variables (ID: rw-migration-aou-rw-f7a4d148)
Found bucket: id=temporary-workspace-bucket, bucketName=temporary-workspace-bucket-wb-perky-cabbage-8342
Found bucket: id=workspace-bucket, bucketName=workspace-bucket-wb-perky-cabbage-8342
✅ Successfully identified latest dataset: wb-silky-artichoke-2408.C2024Q3R9

Variables extracted:
GOOGLE_CLOUD_PROJECT: wb-perky-cabbage-8342
WORKSPACE_BUCKET: gs://workspace-bucket-wb-perky-cabbage-8342
WORKSPACE_TEMP_BUCKET: gs://temporary-workspace-bucket-wb-perky-cabbage-8342
WORKSPACE_CDR: wb-silky-artichoke-2408.C2024Q3R9
bucket_aou_tutorial: NOT FOUND
bucket_id_aou_tutorial: NOT FOUND
bucket_migrated: gs://rw-migration-aou-rw-f7a4d148
bucket_id_migrated: rw-migration-aou-rw-f7a4d148

✅ Saved to /home/jupyter/.bashrc
C2024Q3R9 BQ_DATASET
Multi-trait-GWAS-in-admixed-populations GIT_REPO
dataset_test2 BQ_DATASET
prep_C2024Q3R9 BQ_DATASET
rw-migration-aou-rw-f7a4d148 GCS_BUCKET
temporary-workspace-bucket GCS_BUCKET
workspace-bucket GCS_BUCKET
GOOGLE_CLOUD_PROJECT = wb-perky-cabbage-8342
WORKSPACE_BUCKET = gs://workspace-bucket-wb-perky-cabbage-8342
WORKSPACE_CDR = wb-silky-artichoke-2408.C2024Q3R9
WORKSPACE_BUCKET = gs://workspace-bucket-wb-perky-cabbage-8342
GOOGLE_PROJECT = wb-perky-cabbage-8342

In [2]:
%run /home/jupyter/repos/Multi-trait-GWAS-in-admixed-populations/notebooks/Setting_Env_Variables_p2.ipynb

WORKSPACE_CDR = wb-silky-artichoke-2408.C2024Q3R9
WORKSPACE_BUCKET = gs://workspace-bucket-wb-perky-cabbage-8342
GOOGLE_PROJECT = wb-perky-cabbage-8342
Done! 10 variables saved to: /home/jupyter/repos/Multi-trait-GWAS-in-admixed-populations/notebooks/Setting_Env_Variables_p2.R
Done! 10 variables saved to: /home/jupyter/repos/Multi-trait-GWAS-in-admixed-populations/notebooks/Setting_Env_Variables.sas

# Import library

In [3]:
%load_ext autoreload
%autoreload 2
    
import os
import subprocess
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

# Importation des données issues du notebook `53_BC_WITHIN_5Y_FamilyHistory_Treatment`

In [6]:
# get the bucket name
my_bucket = os.getenv('WORKSPACE_TEMP_BUCKET')

name_of_file_in_bucket = "df_bc_ko_at_inclusion_223k_nb_BC_WITHIN_5Y_GeneticAncestry_biopsy_FamilyHistory.tsv"

df_bc = pd.read_csv(my_bucket +'/'+ name_of_file_in_bucket, sep=',', low_memory=False)
df_bc

,person_id,gender,date_of_birth,ethnicity,self_reported_category,inclusion_date,first_breast_cancer_date,delay_days,delay_years,time_category,...,first_survey_date,last_survey_date,days_last_survey_to_first_survey,Daughter,Mother,Sibling,days_inclusion_to_first_survey,days_inclusion_to_last_survey,days_has_bc_to_first_survey,days_has_bc_to_last_survey
0,7604109,Female,1953-06-15,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,2022-03-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2382559,Female,1988-06-15,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,2022-04-04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2032331,Female,1954-06-15,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,2019-09-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3382692,Female,1957-06-15,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,2018-07-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2537673,Female,1965-06-15,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,2019-03-04,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223201,8122695,Female,2002-06-15,Not Hispanic or Latino,White,2023-06-21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223202,3902303,Female,2003-06-15,Not Hispanic or Latino,White,2022-12-12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223203,9743793,Female,2003-06-15,Not Hispanic or Latino,White,2022-12-27,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223204,4702863,Female,2003-06-15,Not Hispanic or Latino,White,2023-02-24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223205,5294301,Female,2004-06-15,Not Hispanic or Latino,White,2023-03-24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Verification of relatedness

## relatedness_flagged_samples

### Data import

In [31]:
!gcloud storage ls gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness --billing-project=$GOOGLE_PROJECT

gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness.tsv
gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness_flagged_samples.tsv

In [18]:
!gcloud storage cp gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness_flagged_samples.tsv $WORKSPACE_TEMP_BUCKET/ --billing-project=$GOOGLE_PROJECT

Copying gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness_flagged_samples.tsv to gs://temporary-workspace-bucket-wb-perky-cabbage-8342/samples_relatedness_flagged_samples.tsv
  Completed files 1/1 | 238.9kiB/238.9kiB

In [35]:
destination_filename = 'samples_relatedness_flagged_samples.tsv'

my_bucket = os.getenv('WORKSPACE_TEMP_BUCKET')

df_relatedness_flagged = pd.read_csv(my_bucket +'/'+ destination_filename)

In [36]:
df_relatedness_flagged.merge(df_bc, left_on='sample_id', right_on='person_id', how='inner').value_counts('has_bc')

has_bc
0    19182
1      106
Name: count, dtype: int64

## samples_relatedness

In [32]:
!gcloud storage cp gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness.tsv $WORKSPACE_TEMP_BUCKET/ --billing-project=$GOOGLE_PROJECT

Copying gs://vwb-aou-datasets-controlled/v8/wgs/short_read/snpindel/aux/relatedness/samples_relatedness.tsv to gs://temporary-workspace-bucket-wb-perky-cabbage-8342/samples_relatedness.tsv
  Completed files 1/1 | 1.0MiB/1.0MiB

In [40]:
destination_filename = 'samples_relatedness.tsv'

my_bucket = os.getenv('WORKSPACE_TEMP_BUCKET')

df_samples_relatedness = pd.read_csv(my_bucket +'/'+ destination_filename, sep='\t')

In [41]:
df_samples_relatedness

           i.s      j.s      kin
0      1000039  1408407  0.25400
1      1000059  8347825  0.24235
2      1000091  1272257  0.25344
3      1000109  1110298  0.12389
4      1000109  1384467  0.24171
...        ...      ...      ...
39676  9815147  9935206  0.26708
39677  9820941  9846530  0.25047
39678  9879407  9939253  0.25951
39679  9897608  9944031  0.26561
39680  9925038  9990626  0.24334

[39681 rows x 3 columns]

In [38]:
df_samples_relatedness.merge(df_bc, left_on='sample_id', right_on='person_id', how='inner').value_counts('has_bc')

KeyError: 'sample_id'

# Sélection des individus ayant une date de cancer du sein > 180 jours après l'inclusion (3 mois)

# Sélection des individus ayant eu une biopsie < 180 jours avant la date d'inclusion (3 mois)

# Faire colonne délai entre date de cancer et date de questionnaire

# Garder les femmes de 42 à 72 (ou 37 à 42 et ainsi de suite...)

# Data's export

In [ ]:
destination_filename = 'Datas/df_bc_ko_at_inclusion_223k_nb_BC_WITHIN_5Y_GeneticAncestry_biopsy_FamilyHistory.tsv'
df.to_csv(destination_filename, index=False)

# Récupère le nom du bucket Google Cloud depuis la variable d’environnement
my_bucket = os.getenv('WORKSPACE_TEMP_BUCKET')

# Copie le fichier TSV local dans le dossier "Data" du bucket
args = ["gsutil", "cp", f"./{destination_filename}", f"{my_bucket}"]
output = subprocess.run(args, capture_output=True)

# Affiche les éventuelles erreurs retournées par gsutil
output.stderr